testMode: assertion
testLimit: 10000
corpusDir: "corpus"
coverage: true
seqLen: 100
contractAddr: "0x00a329c0648769a73afac7f9381e08fb43dbea72"
deployer: "0x30000"
sender: ["0x10000", "0x20000"]

# Additional arguments to pass to solc directly:
solverArgs:
  - "--allow-paths"
  - "."
  - "--allow-paths"
  - "./lib"
  - "--base-path"
  - "."